### ISSUE TITLE
Axes && Subplots

### ISSUE THREAD

**Issue by VeraZab** [plotly/react-plotly.js-editor#326]
- [x] make axes work for all plots (closed with #331)
- [x] add subplot support (#334)
 - [x] xref/yref in annotations (#334)
